name: ca-plugin
channels:
  - conda-forge
dependencies:
  - geojson-pydantic=1.0.1
  - pip=23.2.1
  - pre-commit=3.6.0
  - pydantic=2.3.0
  - pytest=7.4.2
  - python=3.11.5
  - responses=0.24.1
  - shapely=2.0.2
  - yaml=0.2.5
  - pip:
      - git+https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.gistools.geog.uni-heidelberg.de/climate-action/climatoology.git@v2.6.4
      - ohsome==0.3.0
